import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from skimage import measure
import ezdxf
from pathlib import Path
from shapely.geometry import Polygon
from scipy.ndimage import rotate
import torch
import torch.nn.functional as F
import math
import os
import imageio





def generate_pattern(grid_size , M , N , beta):
    radius_px  = grid_size // 2 - 4 
    # Random Fourier coefficients  c_{mn}^{cos} and c_{mn}^{sin}
    c_cos = rng.normal(scale=1.0, size=(N + 1, M + 1))  # n = 0..N, m = 0..M
    c_sin = rng.normal(scale=1.0, size=(N + 1, M + 1))
    c_sin[:, 0] = 0.0  # the m=0 term has no sine component
    # -----------------------------
    # Build polar grid
    # -----------------------------
    # Coordinates centred at (0,0)
    x = np.linspace(-radius_px, radius_px, grid_size)
    y = np.linspace(-radius_px, radius_px, grid_size)
    X, Y = np.meshgrid(x, y)
    R = np.sqrt(X**2 + Y**2)
    Theta = np.arctan2(Y, X)  # angle in radians

    # Disk mask
    disk = R <= radius_px
    R_norm = R[disk] / radius_px  # normalised radius in [0,1] inside the disk

    # -----------------------------
    # Evaluate the Fourier series
    # -----------------------------
    F = np.zeros_like(R_norm)

    for n in range(N + 1):
        # radial basis: cos(pi n r)
        R_n = np.cos(np.pi * n * R_norm)
        for m in range(M + 1):
            cos_term = c_cos[n, m] * np.cos(m * Theta[disk])
            sin_term = c_sin[n, m] * np.sin(m * Theta[disk])
            F += R_n * (cos_term + sin_term)

    # -----------------------------
    # Soft binarisation via sigmoid
    # -----------------------------
    def sigmoid(z):
        return 1.0 / (1.0 + np.exp(-z))

    mask_soft = sigmoid(beta * F)
    # Threshold at 0.5 to get a binary pattern; keep it soft if you prefer
    mask_binary = (mask_soft < 0.5).astype(np.float32)

    # Build a full image
    image = np.zeros((grid_size, grid_size), dtype=np.float32)
    image[disk] = mask_binary  # values are 0 or 1 inside the disk

    # -----------------------------
    # Visualisation
    # -----------------------------
    # plt.figure(figsize=(6, 6))
    # plt.imshow(image, cmap="gray", origin="lower")
    img_path = "/Users/michael_adlerstein/Desktop/kings stuff /Rheology_code/test_imgs/plate_B_hat.png"
    # # plt.title("Initial plate B' generated by truncated Fourier series")
    # plt.axis("off")
    plt.savefig(img_path, dpi=150, bbox_inches="tight")
    # plt.show()

    diameter_px = 2 * radius_px + 1                # e.g. 505 for grid_size = 512
    start = (grid_size - diameter_px) // 2        # left/top index
    end   = start + diameter_px

    mask_crop = image[start:end, start:end]        # shape (D, D)

    # ---------------------------------
    # ❷ Create an RGBA image with
    #    transparent background
    # ---------------------------------
    rgb = (mask_crop * 255).astype(np.uint8)       # 0 or 255
    alpha = rgb.copy()                             # same values for alpha
    rgba = np.stack([rgb, rgb, rgb, alpha], axis=-1)

    rgba_img = Image.fromarray(rgba, mode="RGBA")

    out_path = "/Users/michael_adlerstein/Desktop/kings stuff /Rheology_code/plate_B_hat.png"
    rgba_img.save(out_path, dpi=(300, 300))        # change dpi to taste
    print("saved:", out_path)

    return image

def compute_overlap(image1, image2, angle_deg):
    """
    Rotate image2 by angle_deg around its center, then compute overlap of white pixels with image1.
    Both image1 and image2 must be square binary images (values 0 or 1).
    """
    # Ensure binary masks
    mask1 = (image1 > 0.5).astype(np.float32)
    mask2 = (image2 > 0.5).astype(np.float32)

    # Rotate mask2 around the center
    rotated_mask2 = rotate(mask2, angle=angle_deg, reshape=False, order=1)

    # Compute overlap of white pixels (where both masks are 1)
    overlap = mask1 * rotated_mask2
    overlap_area = np.sum(overlap)
    return overlap_area



def area_sweep(image1, image2 ):
    theta = np.linspace(0 , 360 , 361)
    rot_area = []
    for i in theta:
        area_i = compute_overlap(image1 , image2 , angle_deg = i)
        rot_area.append(area_i)

    return rot_area
def generate_pattern_torch(grid_size, M, N, beta, c_cos, c_sin):
    device = c_cos.device
    radius_px = grid_size // 2 - 4

    x = torch.linspace(-radius_px, radius_px, grid_size, device=device)
    y = torch.linspace(-radius_px, radius_px, grid_size, device=device)
    Y, X = torch.meshgrid(y, x, indexing='ij')
    R = torch.sqrt(X**2 + Y**2)
    Theta = torch.atan2(Y, X)
    R_norm = R / radius_px

    F = torch.zeros_like(R_norm)

    for n in range(N + 1):
        R_n = torch.cos(math.pi * n * R_norm)
        for m in range(M + 1):
            F += R_n * (
                c_cos[n, m] * torch.cos(m * Theta) +
                c_sin[n, m] * torch.sin(m * Theta)
            )

    mask_soft = torch.sigmoid(beta * F)
    disk = (R <= radius_px).float()
    image = mask_soft * disk  # fully differentiable
    return image

def rotate_tensor(image, angle_deg):
    angle_rad = -angle_deg * math.pi / 180
    theta = torch.tensor([
        [math.cos(angle_rad), -math.sin(angle_rad), 0.0],
        [math.sin(angle_rad),  math.cos(angle_rad), 0.0]
    ], dtype=torch.float32, device=image.device).unsqueeze(0)
    grid = F.affine_grid(theta, image.size(), align_corners=False)
    return F.grid_sample(image, grid, mode='bilinear', padding_mode='zeros', align_corners=False)

def compute_overlap_torch(image1, image2, angle_deg):
    if image1.ndim == 2:
        image1 = image1.unsqueeze(0).unsqueeze(0)
    if image2.ndim == 2:
        image2 = image2.unsqueeze(0).unsqueeze(0)
    rotated = rotate_tensor(image2, angle_deg)
    return (image1 * rotated).sum()

def area_sweep_torch(image1, image2, angles=torch.linspace(0, 360, 72)):
    return torch.stack([compute_overlap_torch(image1, image2, a.item()) for a in angles])


if __name__ == "__main__":

    # -------------------------
    # Setup
    # -------------------------
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    M, N, grid_size = 2, 2, 64
    beta = 10.0

    c_cos = torch.nn.Parameter(torch.randn(N + 1, M + 1, device=device))
    c_sin = torch.nn.Parameter(torch.randn(N + 1, M + 1, device=device))
    with torch.no_grad():
        c_sin[:, 0] = 0.0

    c_cos2 = torch.nn.Parameter(torch.randn(N + 1 , M + 1, device=device))
    c_sin2 = torch.nn.Parameter(torch.randn(N + 1, M + 1, device=device))
    with torch.no_grad():
        c_sin2[:, 0] = 0.0



    # Ground truth pattern (frozen)
    with torch.no_grad():
        target_image = generate_pattern_torch(grid_size, M, N, beta, c_cos, c_sin).detach()

    with torch.no_grad():
        target2_image = generate_pattern_torch(grid_size, M, N, beta, c_cos2, c_sin2).detach()

    # New random params to train
    c_cos_B = torch.nn.Parameter(torch.randn(N + 1, M + 1, device=device))
    c_sin_B = torch.nn.Parameter(torch.randn(N + 1, M + 1, device=device))
    with torch.no_grad():
        c_sin_B[:, 0] = 0.0

    optimizer = torch.optim.Adam([c_cos_B, c_sin_B], lr=0.04)

    # Reference overlap (no grad)
    with torch.no_grad():
        overlap_ref = area_sweep_torch(target_image, target2_image)

    # -------------------------
    # Training loop
    # -------------------------
    loss_history = []
    angle_plot=torch.linspace(0, 360, 72)

    for epoch in range(1000):
        optimizer.zero_grad()
        #generate a starting plate for B
        pattern_B = generate_pattern_torch(grid_size, M, N, beta, c_cos_B, c_sin_B)
        area_pred = area_sweep_torch(target_image, pattern_B)
        loss = F.mse_loss(area_pred, overlap_ref)
        loss.backward()

        with torch.no_grad():
            c_sin_B.grad[:, 0] = 0.0

        optimizer.step()
        loss_history.append(loss.item()) 

        if epoch % 10 == 0:
            print(f"Epoch {epoch}, Loss = {loss.item():.4f}")

            # Detach tensors for plotting
            target_pattern1 = target_image.detach().cpu().numpy()
            target_pattern2 = target2_image.detach().cpu().numpy()
            current_pattern = pattern_B.detach().cpu().numpy()
            area_pred_np = area_pred.detach().cpu().numpy()
            overlap_ref_np = overlap_ref.detach().cpu().numpy()

            # Plot: 3 images (target1, target2, optimized) + overlap curve
            fig = plt.figure(figsize=(15, 8))

            # Target image 1
            ax1 = fig.add_subplot(2, 3, 1)
            ax1.imshow(target_pattern1, cmap='gray', origin='lower')
            ax1.set_title("Plate A ")
            ax1.axis('off')

            # Target image 2
            ax2 = fig.add_subplot(2, 3, 2)
            ax2.imshow(target_pattern2, cmap='gray', origin='lower')
            ax2.set_title("Plate B (Target)")
            ax2.axis('off')

            # Current optimized image
            ax3 = fig.add_subplot(2, 3, 3)
            ax3.imshow(current_pattern, cmap='gray', origin='lower')
            ax3.set_title(f"Optimized Pattern (Epoch {epoch})")
            ax3.axis('off')
    
            # Overlap curve
            ax4 = fig.add_subplot(2, 1, 2)
            ax4.plot(angle_plot , overlap_ref_np,  label='Target Overlap')
            ax4.plot( angle_plot , area_pred_np, label='Predicted Overlap')
            ax4.set_title("Overlap Curve Comparison")
            ax4.set_xlabel("Angle (degrees)")
            ax4.set_ylabel("Overlap Area")
            ax4.legend()
            ax4.grid(True)

            plt.tight_layout()

            # Make a folder for frames
            frame_dir = "/Users/michael_adlerstein/Desktop/kings stuff /Rheology_code/results"
            os.makedirs(frame_dir, exist_ok=True)

            # Inside the training loop, replace plt.show() with:
            frame_path = os.path.join(frame_dir, f"frame_{epoch:04d}.png")
            plt.savefig(frame_path, dpi=150)
            plt.close()

            # Collect frame paths in order
            frames = sorted([os.path.join(frame_dir, f) for f in os.listdir(frame_dir) if f.endswith('.png')])

            # Write to GIF
            gif_path = "optimization_progress.gif"
            with imageio.get_writer(gif_path, mode='I', duration=0.5) as writer:
                for frame in frames:
                    image = imageio.imread(frame)
                    writer.append_data(image)

            print(f"GIF saved to {gif_path}")