import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from skimage import measure
import ezdxf
from pathlib import Path
from compute_area import extract_closed_polylines , intersection_area, intersection_area , compute_total_area
from shapely.geometry import Polygon


units = 0.001  # Set to 0.001 if drawing is in mm; 1.0 if already in meters



# -----------------------------
# Parameters you can play with
# -----------------------------
grid_size = 512      # number of pixels in x and y
radius_px  = grid_size // 2 - 4   # radius of the disk in pixels
M = 6               # highest angular harmonic m
N = 4               # highest radial index n
beta = 20.0         # steepness of the sigmoid (larger -> closer to binary)

rng = np.random.default_rng(seed=2025)  # reproducible randomness

# Random Fourier coefficients  c_{mn}^{cos} and c_{mn}^{sin}
c_cos = rng.normal(scale=1.0, size=(N + 1, M + 1))  # n = 0..N, m = 0..M
c_sin = rng.normal(scale=1.0, size=(N + 1, M + 1))
c_sin[:, 0] = 0.0  # the m=0 term has no sine component

# -----------------------------
# Build polar grid
# -----------------------------
# Coordinates centred at (0,0)
x = np.linspace(-radius_px, radius_px, grid_size)
y = np.linspace(-radius_px, radius_px, grid_size)
X, Y = np.meshgrid(x, y)
R = np.sqrt(X**2 + Y**2)
Theta = np.arctan2(Y, X)  # angle in radians

# Disk mask
disk = R <= radius_px
R_norm = R[disk] / radius_px  # normalised radius in [0,1] inside the disk

# -----------------------------
# Evaluate the Fourier series
# -----------------------------
F = np.zeros_like(R_norm)

for n in range(N + 1):
    # radial basis: cos(pi n r)
    R_n = np.cos(np.pi * n * R_norm)
    for m in range(M + 1):
        cos_term = c_cos[n, m] * np.cos(m * Theta[disk])
        sin_term = c_sin[n, m] * np.sin(m * Theta[disk])
        F += R_n * (cos_term + sin_term)

# -----------------------------
# Soft binarisation via sigmoid
# -----------------------------
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

mask_soft = sigmoid(beta * F)
# Threshold at 0.5 to get a binary pattern; keep it soft if you prefer
mask_binary = (mask_soft > 0.5).astype(np.float32)

# Build a full image
image = np.zeros((grid_size, grid_size), dtype=np.float32)
image[disk] = mask_binary  # values are 0 or 1 inside the disk

# -----------------------------
# Visualisation
# -----------------------------
plt.figure(figsize=(6, 6))
plt.imshow(image, cmap="gray", origin="lower")
img_path = "/Users/michael_adlerstein/Desktop/kings stuff /Rheology_code/plate_B_hat.png"
# plt.title("Initial plate B' generated by truncated Fourier series")
plt.axis("off")
plt.savefig(img_path, dpi=150, bbox_inches="tight")

plt.show()

diameter_px = 2 * radius_px + 1                # e.g. 505 for grid_size = 512
start = (grid_size - diameter_px) // 2        # left/top index
end   = start + diameter_px

mask_crop = image[start:end, start:end]        # shape (D, D)

# ---------------------------------
# ❷ Create an RGBA image with
#    transparent background
# ---------------------------------
rgb = (mask_crop * 255).astype(np.uint8)       # 0 or 255
alpha = rgb.copy()                             # same values for alpha
rgba = np.stack([rgb, rgb, rgb, alpha], axis=-1)

from PIL import Image
rgba_img = Image.fromarray(rgba, mode="RGBA")

out_path = "/Users/michael_adlerstein/Desktop/kings stuff /Rheology_code/plate_B_hat.png"
rgba_img.save(out_path, dpi=(300, 300))        # change dpi to taste
print("saved:", out_path)



png_path = Path("/Users/michael_adlerstein/Desktop/kings stuff /Rheology_code/plate_B_hat.png")

desired_circle_mm = 50.0          # the green circle *inside* the shape
# ---------------------------------------------------------------
# 1.  load  alpha channel → hard mask
# ---------------------------------------------------------------
img_rgba = Image.open(png_path).convert("RGBA")
rgba     = np.asarray(img_rgba)
alpha     = rgba[..., 3]                          # 0..255
mask_raw  = (alpha > 128).astype(np.uint8)        # 1 = Fourier lobes
disk_mask = np.ones_like(mask_raw, dtype=np.uint8)
r, c      = np.indices(mask_raw.shape)
center_r, center_c = (np.array(mask_raw.shape) - 1) / 2
radius_px = mask_raw.shape[0] // 2 - 4            # same as earlier
inside    = (r-center_r)**2 + (c-center_c)**2 <= radius_px**2
disk_mask[~inside] = 0                            # outside the circle

# -------- desired plate area = disk minus Fourier lobes -------------
mask = disk_mask - mask_raw       # 1 = solid plate, 0 = cut-outs
# ---------------------------------------------------------------
# 2.  find *all* contours, keep exterior & holes separately
#    coordinates come as (row, col) pixel floats
# ---------------------------------------------------------------
contours = measure.find_contours(mask, 0.5)
if not contours:
    raise RuntimeError("No contour found in PNG.")

# -----------------------------------------------------------------
# 3.  geometric centre & mm-per-pixel scale
#     • centre_px  = centroid of all opaque pixels
#     • scale_mm_per_px chosen so the final green circle has
#       radius = desired_circle_mm
# -----------------------------------------------------------------
rows, cols = np.nonzero(mask)                       # opaque pixels
centre_px = np.array([rows.mean(), cols.mean()])    # (row, col)

# pixel-radius of every contour vertex
all_pts  = np.vstack(contours)                      # (k, 2)  [row, col]
radii_px = np.hypot(all_pts[:, 1] - centre_px[1],
                    all_pts[:, 0] - centre_px[0])

# ---------------------------------------------------------------
#  choose scaling mode
# ---------------------------------------------------------------
use_inscribed = True       # True  → polygon INSIDE the circle
                           # False → circle  INSIDE the polygon

if use_inscribed:
    radius_px = radii_px.max()      # largest vertex → inscribed
else:
    radius_px = radii_px.min()      # smallest vertex → circumscribed

scale_mm_per_px = desired_circle_mm / radius_px    # final scale factor
# ---------------------------------------------------------------
# 4.  write DXF
# ---------------------------------------------------------------
doc = ezdxf.new(dxfversion="R2013")
msp = doc.modelspace()

# inner reference circle (green)
msp.add_circle((0, 0), desired_circle_mm,
               dxfattribs={"layer": "0", "color": 3})

# every contour → LWPOLYLINE
for cnt in contours:
    x_mm = (cnt[:, 1] - centre_px[1]) * scale_mm_per_px
    y_mm = -(cnt[:, 0] - centre_px[0]) * scale_mm_per_px  # invert Y
    msp.add_lwpolyline(list(zip(x_mm, y_mm)),
                       format="xy",
                       close=True,
                       dxfattribs={"layer": "0", "color": 5})

# save
dxf_path = png_path.with_suffix(".dxf")
doc.saveas(dxf_path)
print("DXF written →", dxf_path)



def plot_dxf(file_path):
    doc = ezdxf.readfile(file_path)
    msp = doc.modelspace()

    fig, ax = plt.subplots()
    ax.set_aspect("equal")
    ax.set_title(f"DXF view — {file_path}")

    for ent in msp:
        etype = ent.dxftype()

        if etype == "LINE":
            s, e = ent.dxf.start, ent.dxf.end
            ax.plot([s.x, e.x], [s.y, e.y], "k-")

        elif etype == "LWPOLYLINE":
            pts = np.array(ent.get_points("xy"))[:, :2]   # (n,2)
            if getattr(ent, "closed", False):
                pts = np.vstack([pts, pts[0]])           # close loop
            ax.plot(pts[:, 0], pts[:, 1], "b-")

        elif etype == "CIRCLE":
            c   = ent.dxf.center                # Vec3
            rad = ent.dxf.radius
            ax.add_patch(plt.Circle((c.x, c.y), rad,
                                    fill=False, color="g"))

        elif etype == "ARC":
            c   = ent.dxf.center
            r   = ent.dxf.radius
            a0, a1 = ent.dxf.start_angle, ent.dxf.end_angle
            ang = np.linspace(a0, a1, 180)
            x = c.x + r * np.cos(np.deg2rad(ang))
            y = c.y + r * np.sin(np.deg2rad(ang))
            ax.plot(x, y, "r--")

    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.grid(True)
    plt.show()


# plot_dxf(dxf_path)


def to_plate(poly_or_list):
    """Return a single Polygon (outer − holes) from list or Polygon."""
    if isinstance(poly_or_list, Polygon):
        return poly_or_list
    # list case
    outer = max(poly_or_list, key=lambda p: p.area)
    holes = [p.exterior.coords[:] for p in poly_or_list if p is not outer]
    return Polygon(outer.exterior.coords, holes)



if __name__ == "__main__":

    dxf_file_1 = "/Users/michael_adlerstein/Desktop/kings stuff /Rheology_code/pattern1.dxf"  # Replace with your DXF filename
    dxf_file_2 = "/Users/michael_adlerstein/Desktop/kings stuff /Rheology_code/plate_B_hat.dxf"  # Replace with your DXF filename

    units = 0.001  # Set to 0.001 if drawing is in mm; 1.0 if already in meters

    shape_1 = extract_closed_polylines(dxf_file_1)
    shape_2 = extract_closed_polylines(dxf_file_2)
    plate_B = to_plate(shape_2)                       # Polygon afterwards
    area_m1 = compute_total_area(shape_1, units_to_meters=units)
    area_m2 = compute_total_area(plate_B, units_to_meters=units)
    inter_area = intersection_area(shape_1 , plate_B)

    print(area_m1 , area_m2)
    print(inter_area)
    plot_dxf(dxf_file_1) 
    plot_dxf(dxf_file_2) 
    pass 
